### ISSUE TITLE
Card Height

### ISSUE THREAD

**Issue by enegadi** [Haitam-Elgharras/game-hub#1]
Try to fix the card height; some cards are different from the others

![Screenshot 2024-01-07 231738](https://github.com/Haitam-Elgharras/game-hub/assets/79484826/57892061-9daf-41c3-8fb5-5d5e4f0e33e0)

**Comment by Haitam-Elgharras** [comment]
Hi @enegadi,
Thank you for bringing up the issue regarding the varying card heights in the GameHub repository. After investigating the issue, it seems that the discrepancy in card heights is primarily caused by differences in the length of the game names.
Do you have any propositions on how we could address this issue?
